### ISSUE TITLE
Exemplos não funcionaram

### ISSUE THREAD

**Issue by ribafs** [DenisPower1/inter#16]
Achei o projeto muito interessante e aprece legal.
Mas testei local e com o CDN, mas a variaǘem mensagem não é substituída.

**Comment by DenisPower1** [comment]
> Achei o projeto muito interessante e aprece legal.
> Mas testei local e com o CDN, mas a variaǘem mensagem não é substituída.

Tudo bem mano? 
Podes me informar o nome e a versão do teu navegador?

O Inter(o framework) foi testado na maioria dos navegadores modernos e não teve nenhum problema.

Tente fazer o seguinte:

* Certifique-se que o framework está sendo devidamente importado na página.
* Certifique-se que o código esteja correto.
* Vai ao console do navegador e vê se o Inter está te notificando de algum erro cometido.

E o framework não suporta os Internet explorer.

**Comment by ribafs** [comment]
Uso o Firefox 89.0.2 no Linux Mint 20.1

Na página
http://interjs.epizy.com/v1/tutorial/pt/introducao/

Quando clico em próximo dá 404

Na console somente me diz:

You're using Inter in development mode, when you deploy your app turn on production mode.

Mesmo que eu esteja usando 

<script>
app.status="Production";

**Comment by DenisPower1** [comment]
> Uso o Firefox 89.0.2 no Linux Mint 20.1
> 
> Na página
> http://interjs.epizy.com/v1/tutorial/pt/introducao/
> 
> Quando clico em próximo dá 404
> 
> Na console somente me diz:
> 
> You're using Inter in development mode, when you deploy your app turn on production mode.
> 
> Mesmo que eu esteja usando
> 
> <script> app.status="Production"; Fiz o seguinte teste hoje: <title>Document</title> <script src="inter.min.js"></script>
> { mensagem }
> 
> { toggle }
> <script> app.status="Production"; toHTML({ in:"exemplo", data:{ mensagem:" ", toggle:"Guardar" }, react:"trocar" }) toATTR({ in:"exemplo", data:{ gerenciarinput:{ value:"", onkeyup(){ trocar.toggle="Guardar" if(gerenciarinput.value.trim().length==0){ gerenciarbutao.disabled=true; }else{ gerenciarbutao.disabled=null; } }, placeholder:"Teu nome", }, gerenciarbutao:{ disabled:true, onclick(){ trocar.toggle="Guardado"; trocar.mensagem=gerenciarinput.value; this.disabled=true; } } } }) <script>
> E o navegador mostra
> 
> { mensagem }
> 
> E { toggle } no botão

Na verdade para acionar o versão produção tem que ser:

```Javascript
//production e não Production. 
app.status="production";
```

Eu pude notar que esse exemplo está na documentação, quando você leu a documentação os exemplos também não funcionavam lá?

Tente  usar esse exemplo:

```html
<div id="testando">
<p>{  mensagem } </p>
</div>
````
```Javascript
toHTML({
in:"testando",
data:{
mensagem:"Funcionou!"
}
})
```

E importa o framework usando o seguinte link : 

```Javascript
<script src="https://cdn.jsdelivr.net/gh/DenisPower1/inter@1.1.3/inter.min.js""></script>
```

E se não for um incomodo, serás que podes postar o código que tentas fazer com o framework no codepen? Assim será mais simples diagnosticar o erro.

**Comment by DenisPower1** [comment]
> Uso o Firefox 89.0.2 no Linux Mint 20.1
> 
> Na página
> http://interjs.epizy.com/v1/tutorial/pt/introducao/
> 
> Quando clico em próximo dá 404
> 
> Na console somente me diz:
> 
> You're using Inter in development mode, when you deploy your app turn on production mode.
> 
> Mesmo que eu esteja usando
> 
> <script> app.status="Production"; Fiz o seguinte teste hoje: <title>Document</title> <script src="inter.min.js"></script>
> { mensagem }
> 
> { toggle }
> <script> app.status="Production"; toHTML({ in:"exemplo", data:{ mensagem:" ", toggle:"Guardar" }, react:"trocar" }) toATTR({ in:"exemplo", data:{ gerenciarinput:{ value:"", onkeyup(){ trocar.toggle="Guardar" if(gerenciarinput.value.trim().length==0){ gerenciarbutao.disabled=true; }else{ gerenciarbutao.disabled=null; } }, placeholder:"Teu nome", }, gerenciarbutao:{ disabled:true, onclick(){ trocar.toggle="Guardado"; trocar.mensagem=gerenciarinput.value; this.disabled=true; } } } }) <script>
> E o navegador mostra
> 
> { mensagem }
> 
> E { toggle } no botão

Dê uma olhada nesse exemplo no codepen:

 [Exemplo no codepen](https://codepen.io/Denis-Power/pen/jOmbQjK)

**Comment by ribafs** [comment]
Este exemplo funcionou, mas a biblioteca deve ser inserida no início do arquivo.
Obrigado

**Comment by DenisPower1** [comment]
> Este exemplo funcionou, mas a biblioteca deve ser inserida no início do arquivo.
> Obrigado

É isso mesmo, ele deve estar no início da página e antes do teu código,  vou fechar aqui o issue, se você comentar sobre esse framework para um conhecido seu, estarás ajudando bastante.

E se divirta programando com o Inter!
