### ISSUE TITLE
Hello world - contribuição

### ISSUE THREAD

**Issue by brutalzinn** [DenisPower1/inter#19]
Olá, gostei do conceito empregado nessa lib. Como posso ajudar e contribuir com o projeto ?

**Comment by DenisPower1** [comment]
> Olá, gostei do conceito empregado nessa lib. Como posso ajudar e contribuir com o projeto?

Olá!

Bem, se você gostou dos conceitos do framework eu creio que outros programadores gostarão também, então, se você comentar/ensinar sobre o Inter(o framework) para os outros programadores estarás contribuindo muito.

E você deve ter natado que ainda não há uma versão inglesa para [tutorial](http://interjs.epizy.com/v1/tutorial/pt/instalacao/) isso quer dizer que você também pode contribuir ajudando na tradução do tutorial oficial.

# Outras forma de contribuir

Reportar bugs.
Sugerir novas funcionalidades.
Criar libs para empoderar o ecossistema do framework.
Corrigir bugs.

**Comment by brutalzinn** [comment]
Acho que seria legal modular a biblioteca e dividir as responsabilidades por módulos, ou por classes.. Acho que fica difícil executar manutenções, correções e implementações na forma atual. Gostaria de contribuir com algo nesse tipo.

**Comment by DenisPower1** [comment]
Claro @brutalzinn, então até lá!
